name: android-ci

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm ci --legacy-peer-deps

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          sdkmanager --install "platform-tools" "build-tools;34.0.0" "platforms;android-34"

      - name: Make Gradle executable
        run: chmod +x android/gradlew

      - name: Build Release APK
        run: cd android && ./gradlew assembleRelease -x lint

      - name: Upload APK artifact (Vinka.apk)
        uses: actions/upload-artifact@v4
        with:
          name: Vinka.apk
          path: android/app/build/outputs/apk/release/Vinka.apk
